add arp support
JulianSchmid/etherparse pull request #103
Opened 2024-07-02 07:04 UTC by lieka1

Hi there!  i dont' know if you are accepting any pr for arp support

added: 
SlicedPacket::from_ethernet is now supporting arp EtherType
PacketBuilderStep<ArpHeader> is added to build arp header

but LaxSlicedPacket::from_ethernet still cannot parse arp package, i am not sure if is should add it since arp header is quite short

2024-07-03 19:49 UTC, JulianSchmid commented
Hi @lieka1 ,

I will have a look at your PR this weekend. Thanks in advance.

Greets
Julian

2024-07-10 11:12 UTC, JulianSchmid requested changes
Hi @lieka1,

Firstly thanks for the PR, I like the implementation. But I have some issues that would need to be fixed up before I can merge it (see comments).

Concerning the lax implementation, I would say it is needed before I can release the next version. But you don't have to do it, I can also add it after I merged your PR. But let me know if you want to do it, then I don't start on it.

Greets
Julian

2024-07-10 12:20 UTC, lieka1 commented
@JulianSchmid Thank you for your patients, sorry for the bug, i didn't run the test before the pr, my bad.

Of course i can do it, i feel good to do some contribution to open source

2024-07-11 16:01 UTC, lieka1 commented
@JulianSchmid I am not adding any test for it, i barely understand how test is working, i think i just leave it to someone know more about it.

may be rename src/err/ip to src/err/net just to be consistant? 
i also not moving src/link/arp_header.rs and src/link/arp_payload.rs

2024-07-11 17:28 UTC, JulianSchmid commented
> @JulianSchmid I am not adding any test for it, i barely understand how test is working, i think i just leave it to someone know more about it.

That is fine, I will have a look later if I add one.

> may be rename src/err/ip to src/err/net just to be consistant? 

Yes, that is fine by me. There might be some really ip specific stuff I would leave in `ip`. But that is not really important right now. I will have a look later, there anyways is some work that needs to be done there.

> i also not moving src/link/arp_header.rs and src/link/arp_payload.rs to src/net

👍

2024-10-31 08:06 UTC, nine-point-eight-p commented
Hi! I'm also interested in adding ARP to this library, and I found this PR before starting by myself. I wonder if you guys are still working on it?

2024-11-01 17:39 UTC, JulianSchmid commented
Hi @nine-point-eight-p ,

I started working on it a bit more but did not finish yet. I will try to have another pass this weekend and push the result and then let you know what the state is (if I just push an update and you could have a look or if I am able to finish it).

Greets
Julian

2024-11-11 06:12 UTC, JulianSchmid commented
Hi @nine-point-eight-p ,

I did further rework on the ARP implementation and pushed it to the branch `arp-followup` https://github.com/JulianSchmid/etherparse/tree/arp-followup . I am still not finished and I think it would need a few more passes.

Currently I think it makes no sense if you help there, I still want to change a few fundamental things there. But thanks for the offer.

Greets
Julian

2025-01-13 20:37 UTC, JulianSchmid approved these changes

2025-01-13 20:42 UTC, merged