Implement PacketBuilderStep<IpHeader>.write
JulianSchmid/etherparse pull request #27
Opened 2022-03-03 16:26 UTC by karpawich

Resolves #26

@JulianSchmid : what is missing from this PR? I can help write tests, docs, etc. but I want to ask you for your guidance first.

2022-03-04 15:25 UTC, JulianSchmid commented
Hi @karpawich ,

I don't know when I get around to reviewing your PR in depth. But add some tests here https://github.com/JulianSchmid/etherparse/blob/master/tests/packet_builder/mod.rs  for the new code paths you added.

You can use the coverage report to find holes and use the script https://github.com/JulianSchmid/etherparse/tree/master/scripts to calculate a coverage report locally.

Greets & 1000 Thanks
Julian

2022-03-04 15:26 UTC, JulianSchmid commented
I forgot to mention: Thanks for the PR :)

2022-07-14 05:25 UTC, karpawich commented
I have written the tests. I still need to update the documentation.

N.B: The `protocol` argument of the `Ipv4Header::new` function needs to be of type `u8` instead of `IpNumber` to support the use of unassigned IP numbers.

2022-07-14 10:29 UTC, JulianSchmid commented
Hi @karpawich , I will try to have a look at your PR this weekend.

2022-07-16 18:42 UTC, JulianSchmid requested changes
Some minor changes that I will commit in a second.

2022-07-16 18:43 UTC, JulianSchmid commented on src/packet_builder.rs
> +    ///             IpNumber::Udp as u8, //will be replaced during write
```suggestion
    ///             ip_number::UDP, //will be replaced during write
```

2022-07-17 08:57 UTC, JulianSchmid requested changes
I did another review round. You don't have to do anything I already have a commit ready with fixes to address the comments.

2022-07-17 08:57 UTC, JulianSchmid commented on src/packet_builder.rs
> +                    ip.write(writer)?;
Missing write of extension headers

2022-07-17 08:57 UTC, JulianSchmid commented on src/packet_builder.rs
> +                    ip.write(writer)?;
Missing write of extension headers

2022-07-17 08:57 UTC, JulianSchmid commented on src/packet_builder.rs
> +                    ip.set_payload_length(payload.len())?;
length of the extension headers

2022-07-17 08:57 UTC, JulianSchmid commented on src/packet_builder.rs
> +                    ip.set_payload_len(payload.len())?;
length of the extension headers

2022-07-17 08:57 UTC, JulianSchmid commented on src/packet_builder.rs
> +    pub fn write<T: io::Write + Sized>(self, writer: &mut T, payload: &[u8]) -> Result<(),WriteError> {
I would add the last ip_number as an argument here so it can be set in the last extension header or ip header.

2022-07-17 09:56 UTC, JulianSchmid approved these changes

2022-07-17 12:52 UTC, merged