Add serde derive macros where applicable
JulianSchmid/etherparse pull request #43
Opened 2022-12-17 14:40 UTC by daviessm

I had a requirement to serialize packets. What would you think of adding `serde` support to the package, behind a feature flag?

2022-12-17 14:52 UTC, JulianSchmid commented
Hi @daviessm ,

I like it, but I would as you proposed put it behind a non default feature flag.

Greets
Julian

2022-12-17 15:11 UTC, JulianSchmid requested changes

2022-12-17 15:11 UTC, JulianSchmid commented on src/transport/tcp.rs
> +    #[cfg_attr(feature = "serde", serde(skip), serde(default = "default_options_buffer"))]
I think a manual implementation of `Serialize` & `Deserialize` is needed for `TcpHeader` as well. Only the parts of the `options_buffer` that is actually filled should be serialized and/or deserialized. The length of actually filled data in the options_buffer is defined by the `_data_offset` field. The `_data_offset` field itself can be skipped as it is implicitly encoded in the length of the `options_buffer`.

We could also think about instead serializing the decoded options if that is possible. But that is maybe overkill.

2022-12-17 15:11 UTC, JulianSchmid commented on src/internet/ipv4.rs
>      options_buffer: [u8;40]
Same as with the `TcpHeader` & `Ipv6RawExtension` I would implement `Serialize` & `Deserialize` manually as options buffer is not required to be fully filled (see comments there).

2022-12-17 15:12 UTC, JulianSchmid commented
Sorry I forgot: Thanks for the pull request 👍 .

2022-12-18 11:14 UTC, daviessm commented
Hi @JulianSchmid, thanks for the review! I implemented this because I thought I needed it in a project but ended up writing a custom serializer in my code instead so I won't have any time to work on this any more. I'd be happy for this to be closed or taken over by someone else, whatever works best for you.

2022-12-18 12:41 UTC, JulianSchmid commented
Hi @daviessm , then I would take over the PR and implement it.

2022-12-18 12:45 UTC, merged

2022-12-18 12:58 UTC, JulianSchmid commented
I moved to branch to this repo and opened up a new PR https://github.com/JulianSchmid/etherparse/pull/45